import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useContext } from 'react';
import { LanguageContext } from '@/lib/contexts/languageContext';
import Image from 'next/image';

type Props = {
  frContent: {
    title: string;
    description: {
      greeting: string;
      occupation: string;
    }
  };
  enContent: {
    title: string;
    description: {
      greeting: string;
      occupation: string;
    }
  };
}

export default function Home({frContent, enContent}: Props) {
  const {language} = useContext(LanguageContext);
  const content = language === "fr" ? frContent : enContent;
  return (
    <>
      <Head>
        <title>Nabil Bekka | Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/NB.png" />
      </Head>
      <main>
        <div className={styles.homePage}>
          <div className={styles.presentation}>
            <p className={styles.p}>{content.description.greeting}</p>
            <h1 className={styles.h1}>Nabil Bekka</h1>
            <h2 className={styles.h2}>{content.description.occupation}</h2>
          </div>
          <Image 
            src="/images/NB.png"
            height={440}
            width={383}
            alt={language==='fr' ? 'Photo de profil' : 'Profil picture'}
          />
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const content = await import('@/lib/datas/siteContent.json');
  const frContent = content.french;
  const enContent = content.english;
  return {
    props: {
      frContent,
      enContent
    }
  }
}