import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useContext } from 'react';
import { LanguageContext } from '@/lib/contexts/languageContext';

type Props = {
  frContent: {
    title: string;
    description: {
      greeting: string;
      occupation: string;
    }
  };
  enContent: {
    title: string;
    description: {
      greeting: string;
      occupation: string;
    }
  };
}

export default function Home({frContent, enContent}: Props) {
  const {language} = useContext(LanguageContext);
  const content = language === "fr" ? frContent : enContent;
  return (
    <>
      <Head>
        <title>Nabil Bekka | Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.presentation}>
          <h1 className={styles.h1}>{content.description.greeting}</h1>
          <h2 className={styles.h2}>{content.description.occupation}</h2>
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const content = await import('@/lib/datas/siteContent.json');
  const frContent = content.french;
  const enContent = content.english;
  return {
    props: {
      frContent,
      enContent
    }
  }
}